application: gulimuvsign
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /
  script: main.app

- url: /.*
  script: Upload.upload.app
  login: required

- url: /serve*
  script: Upload.upload.app
  login: required

libraries:
- name: django
  version: "1.2"
