application: gulimuvsign
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /
  script: main.app

- url: /upload.*
  script: upload.upload.app
  login: required

- url: /serve.*
  script: upload.upload.app
  login: required

- url: /explore.*
  script: explore.explore.app
  login: required

- url: /about.*
  script: about.about.app

- url: /account.*
  script: account.account.app
  login: required

libraries:
- name: django
  version: "1.2"
